apiVersion: v1
kind: Namespace
metadata:
  name: file-store
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: filestore-server
  name: filestore-server
  namespace: file-store
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: filestore-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: filestore-server
    spec:
      containers:
      - image: riddhiroy/file-store-server:v1
        imagePullPolicy: Always
        name: file-store-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
